### PR TITLE
update assert_sample_shape and expand_tensor_like

### PR DESCRIPTION
**Pull request by kashif**
Update the noise shape helpers to work with multi-dims noise tensors

### CODE REVIEW

**Comment by mhavasi** [comment]
Hey @kashif , thank you for the PR.

Could you give more information on the issue/bug that this PR fixes?

**Comment by kashif** [comment]
so this addresses the fact that the data can be multi-dim e.g. [B, seq_len, dim] and thus the noise for this case will be different for each seq_len, [B, seq_len] and with this change it works with I believe any shape

hope that helps?

**Comment by mhavasi** [comment]
Thank you for the clarification.

This case is solved by flattening the batch dimensions so x_0 and x_1 have the shape [B\*seq_len, dim] and t have the shape [B\*seq_len].

```
sample = my_path.sample(
  x_0=x_0.reshape([B*seq_len, dim], 
  x_1=x_1.reshape([B*seq_len, dim]), 
  t=t.reshape([B*seq_len])
)
x_t = sample.x_t.reshape([B, seq_len, dim])
```

Closing this PR for now, let us know if we misunderstood the problem.

**Comment by kashif** [comment]
right! yes reshaping would also fix it you are right!

**Pull request closed without merging**
